# Agent Prompts

from prompts.prompts import (
    CLASSIFIER_SYSTEM_PROMPT,
    CLASSIFIER_USER_PROMPT,
    REASONING_SYSTEM_PROMPT,
    REASONING_USER_PROMPT,
    ENRICHMENT_SYSTEM_PROMPT,
    ENRICHMENT_USER_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    SUMMARY_USER_PROMPT
)

__all__ = [
    "CLASSIFIER_SYSTEM_PROMPT",
    "CLASSIFIER_USER_PROMPT",
    "REASONING_SYSTEM_PROMPT",
    "REASONING_USER_PROMPT",
    "ENRICHMENT_SYSTEM_PROMPT",
    "ENRICHMENT_USER_PROMPT",
    "SUMMARY_SYSTEM_PROMPT",
    "SUMMARY_USER_PROMPT"
]
